# Generated by Django 6.1 on 2026-08-26 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student registration/roll number.', max_length=50, unique=True, verbose_name='Roll Number / Student ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('photo', models.ImageField(upload_to='students/profiles/', verbose_name='Reference Photo')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('year', models.CharField(max_length=20, verbose_name='Year / Semester')),
                ('suspension_reason', models.TextField(verbose_name='Reason for Suspension')),
                ('suspension_start_date', models.DateField(verbose_name='Suspension Start Date')),
                ('suspension_end_date', models.DateField(verbose_name='Suspension End Date')),
                ('status', models.CharField(choices=[('active', 'Active Suspension'), ('expired', 'Suspension Expired')], default='active', max_length=20, verbose_name='Suspension Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_students', to=settings.AUTH_USER_MODEL, verbose_name='Added By Admin')),
            ],
            options={
                'verbose_name': 'Suspended Student',
                'verbose_name_plural': 'Suspended Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(verbose_name='Serialized Embedding Vector (128-d or 512-d list)')),
                ('model_version', models.CharField(default='sface-128', max_length=50, verbose_name='Model Architecture / Version')),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='students/embeddings/', verbose_name='Source Cropped Face Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='students.suspendedstudent', verbose_name='Suspended Student')),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
                'ordering': ['-created_at'],
            },
        ),
    ]
