"""
Django settings for campusguard project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Automatically load local .env file if present (never tracked in git)
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    with open(_env_file, encoding='utf-8') as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _v = _line.split('=', 1)
                os.environ.setdefault(_k.strip(), _v.strip())

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-campusguard-ai-final-year-project-secret-key-production-ready')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1')

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    
    # CampusGuard AI apps
    'students.apps.StudentsConfig',
    'surveillance.apps.SurveillanceConfig',
    'alerts.apps.AlertsConfig',
    'dashboard.apps.DashboardConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campusguard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'dashboard.context_processors.queue_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'campusguard.wsgi.application'


# Database
# Uses PostgreSQL if DATABASE_URL is set (e.g. Render / Supabase), else local SQLite
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Seamless dual storage: instant static serving in local dev, compressed Whitenoise in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage" if not DEBUG else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Media files (Student photos & live surveillance snapshots)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ==========================================
# CAMPUSGUARD AI CONFIGURATION
# ==========================================

# Confidence Thresholds (Section 4.1 of spec)
CONFIDENCE_THRESHOLD_LOW = 0.65    # 65% - Minimum score for Low-Confidence review queue
CONFIDENCE_THRESHOLD_HIGH = 0.70   # 70% - Minimum score for High-Confidence review queue

# Surveillance Pipeline Settings
FRAME_SAMPLE_RATE = 5              # Process every 5th frame for real-time performance
DEDUPLICATION_COOLDOWN_SECONDS = 180 # Legacy default deduplication window
ALERT_COOLDOWN_SECONDS = 60         # 60s cooldown between automated email alerts for the same person
LOW_CONF_COOLDOWN_SECONDS = 60      # 60s cooldown between low-confidence review queue logs
DEFAULT_CAMERA_SOURCE = 0          # Default to webcam 0
DEFAULT_GATE_LOCATION = "Main Gate - Gate 1"

# Alert System Configuration (Email)
# ----------------------------------------------------------------
# To ACTUALLY send real emails, fill in your Gmail address and
# a Gmail App Password (NOT your regular password).
#
# How to generate a Gmail App Password:
#   1. Go to https://myaccount.google.com/apppasswords
#   2. Select "Mail" and "Windows Computer"
#   3. Click "Generate" and copy the 16-character password
#   4. Paste it below in EMAIL_HOST_PASSWORD
# ----------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('CAMPUSGUARD_EMAIL_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('CAMPUSGUARD_EMAIL_PASSWORD', '').replace(' ', '').strip()
DEFAULT_FROM_EMAIL = os.environ.get('CAMPUSGUARD_DEFAULT_FROM_EMAIL', '') or (f"CampusGuard AI <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else 'CampusGuard AI <alerts@campusguard.local>')
EMAIL_TIMEOUT = 15
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '').strip()

# Authority Alert Recipients (includes EMAIL_HOST_USER if set so tester receives alerts)
_primary_user = os.environ.get('CAMPUSGUARD_EMAIL_USER', '').strip()
ALERT_RECIPIENT_EMAILS = [_primary_user] if _primary_user else []
ALERT_RECIPIENT_EMAILS.extend([
    'security.desk@campus.edu',
    'chief.proctor@campus.edu'
])

# ==========================================
# WhatsApp Alert Configuration (Twilio)
# ==========================================
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', 'whatsapp:+14155238886')
TWILIO_WHATSAPP_CONTENT_SID = os.environ.get('TWILIO_WHATSAPP_CONTENT_SID', '')
# Fallback WhatsApp numbers if none configured in database
ALERT_RECIPIENT_PHONES = [
    '+917671855983'
]


