# Generated by Django 6.1 on 2026-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Chief Security Officer, Dr. Rajesh Sharma (HOD CSE)', max_length=150, verbose_name='Contact / Authority Name')),
                ('email', models.EmailField(help_text='Official email to receive automated security alerts.', max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('security', 'Campus Security Office'), ('hod', 'Department Head (HOD)'), ('proctor', 'Chief Proctor / Disciplinary Committee'), ('warden', 'Hostel Chief Warden'), ('dean', 'Dean of Student Affairs'), ('other', 'Other Authority')], default='security', max_length=50, verbose_name='Authority Role')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Associated Department / Gate (Optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily pause notifications without deleting the contact.', verbose_name='Active (Receive Alerts)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added On')),
            ],
            options={
                'verbose_name': 'Alert Recipient Email',
                'verbose_name_plural': 'Alert Recipient Emails',
                'ordering': ['role', 'name'],
            },
        ),
    ]
