# Generated by Django 6.1 on 2026-09-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrecipient',
            options={'ordering': ['role', 'name'], 'verbose_name': 'Alert Recipient Contact', 'verbose_name_plural': 'Alert Recipient Contacts'},
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Include country code (e.g. +919876543210 or +14155552671)', max_length=30, null=True, verbose_name='WhatsApp / Phone Number'),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Receive Email Alerts'),
        ),
        migrations.AddField(
            model_name='alertrecipient',
            name='send_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Receive WhatsApp Alerts'),
        ),
    ]
