# Generated by Django 6.1 on 2026-08-26 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(default='CAM-01', max_length=50, verbose_name='Camera ID / Stream Source')),
                ('location', models.CharField(default='Main Gate - Entry Point', max_length=150, verbose_name='Gate / Camera Location')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Detection Timestamp')),
                ('confidence_score', models.FloatField(verbose_name='Match Confidence Score (0.0 - 1.0)')),
                ('snapshot_image', models.ImageField(upload_to='snapshots/%Y/%m/%d/', verbose_name='Surveillance Frame Snapshot / Cropped Face')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('low_confidence', 'Low Confidence Queue (70%-85%)'), ('high_confidence', 'High Confidence Queue (>85%)'), ('verified', 'Verified Match (Alert Sent)'), ('rejected', 'Rejected (False Positive)'), ('unmatched', 'Unmatched / Discarded (<70%)')], default='pending', max_length=30, verbose_name='Review Status')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Review Notes')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='Alert Dispatched')),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Alert Sent Timestamp')),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detections', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By Admin')),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='students.suspendedstudent', verbose_name='Matched Suspended Student')),
            ],
            options={
                'verbose_name': 'Detection Log',
                'verbose_name_plural': 'Detection Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
