# Generated by Django 6.1 on 2026-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('low_confidence', 'Low Confidence Queue (65%-70%)'), ('high_confidence', 'High Confidence Queue (>70%)'), ('verified', 'Verified Match (Alert Sent)'), ('rejected', 'Rejected (False Positive)'), ('unmatched', 'Unmatched / Discarded (<65%)')], default='pending', max_length=30, verbose_name='Review Status'),
        ),
    ]
