# Generated by Django 6.1 on 2026-09-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_detectionlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Alert Dispatched'),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp Alert Sent Timestamp'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='alert_sent',
            field=models.BooleanField(default=False, verbose_name='Email Alert Dispatched'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Alert Sent Timestamp'),
        ),
    ]
